name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        java-package: jdk
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jpackageImage
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: h-uppaal-linux
        path: |
          build/jpackage
          
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jpackageImage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: h-uppaal-osx
          path: |
            build/jpackage
            
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
      - name: Build with Gradle
        run: ./gradlew jpackageImage
        working-directory: ${{ github.workspace }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: h-uppaal-windows
          path: |
            build/jpackage
